apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ include "istio-ingressgateway-gcp-wildcard-cert.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "istio-ingressgateway-gcp-wildcard-cert.name" . }}
    helm.sh/chart: {{ include "istio-ingressgateway-gcp-wildcard-cert.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  secretName: istio-ingressgateway-certs
  issuerRef:
    name: {{ include "istio-ingressgateway-gcp-wildcard-cert.fullname" . }}
  commonName: {{ .Values.commonName }}
  acme:
    config:
    - dns01:
        provider: cloud-dns
      domains:
      - "*.example.com"
      - "example.com"
      {{- range .Values.domains }}
      - {{ . | quote }}
      {{- end }}
