apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: {{ include "istio-ingressgateway-gcp-wildcard-cert.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "istio-ingressgateway-gcp-wildcard-cert.name" . }}
    helm.sh/chart: {{ include "istio-ingressgateway-gcp-wildcard-cert.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.issuerEmail }}
    privateKeySecretRef:
      name: {{ include "istio-ingressgateway-gcp-wildcard-cert.fullname" . }}
    dns01:
      providers:
      - name: cloud-dns
        clouddns:
          serviceAccountSecretRef:
            {{- if .Values.existingServiceAccountSecret -}}
            name: {{ .Values.serviceAccountSecretName }}
            {{- else }}
            name: {{ include "istio-ingressgateway-gcp-wildcard-cert.fullname" . }}
            {{- end }}
            key: {{ .Values.serviceAccountSecretKey }}
          project: {{ .Values.gcpProject }}
