{{- if (not .Values.existingServiceAccountSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "istio-ingressgateway-gcp-wildcard-cert.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "istio-ingressgateway-gcp-wildcard-cert.name" . }}
    helm.sh/chart: {{ include "istio-ingressgateway-gcp-wildcard-cert.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{ .Values.serviceAccountSecretKey }}: "{{ .Values.serviceAccountCredentials | b64enc }}"
{{- end }}
