#!/bin/bash

set -xeuo pipefail

#
# Set up a GCP resources for Terraform usage.
#
# 1. Create an admin project for Terraform.
# 2. Enable project services.
# 3. Create a service account for Terraform.
# 4. Create a bucket for Terraform state.
# 5. Barf a Terraform backend file.
# 6. Barf a shell environment file to source for running Terraform.
#

# shellcheck disable=SC1090,SC1091
source "environments/admin/seed.env"

# IAM roles for the admin project to bind to the Terraform service account.
TF_PROJECT_IAM_ROLES=(
  "viewer"
  "storage.admin"
)

# IAM roles for the organization to bind to the Terraform service account.
TF_ORGANIZATION_IAM_ROLES=(
  "resourcemanager.projectCreator"
  "billing.user"
  "dns.admin"
)

# Services to enable.
GCP_SERVICES=(
  "cloudresourcemanager.googleapis.com"
  "cloudbilling.googleapis.com"
  "iam.googleapis.com"
  "compute.googleapis.com"
)

# Create the admin project.
gcloud projects create "${GCP_ADMIN_PROJECT_NAME}" \
  --organization "${GCP_ORGANIZATION_ID}" \
  --set-as-default

# Link billing account.
gcloud beta billing projects link "${GCP_ADMIN_PROJECT_NAME}" \
  --billing-account "${GCP_BILLING_ACCOUNT_ID}"

# Enable services.
for service in "${GCP_SERVICES[@]}"; do
  gcloud services enable "${service}"
done

# Create the service account.
gcloud iam service-accounts create "${TF_SERVICE_ACCOUNT}" \
  --display-name "Terraform account"

# Create the service account's credentials.
# shellcheck disable=SC2086
gcloud iam service-accounts keys create ${TF_CREDENTIALS_FILE} \
  --iam-account "${TF_SERVICE_ACCOUNT}@${GCP_ADMIN_PROJECT_NAME}.iam.gserviceaccount.com"

# Bind project roles to the service account.
for role in "${TF_PROJECT_IAM_ROLES[@]}"; do
  gcloud projects add-iam-policy-binding "${GCP_ADMIN_PROJECT_NAME}" \
    --member "serviceAccount:${TF_SERVICE_ACCOUNT}@${GCP_ADMIN_PROJECT_NAME}.iam.gserviceaccount.com" \
    --role "roles/${role}"
done

# Bind organization roles to the service account.
for role in "${TF_ORGANIZATION_IAM_ROLES[@]}"; do
  gcloud organizations add-iam-policy-binding "${GCP_ORGANIZATION_ID}" \
    --member "serviceAccount:${TF_SERVICE_ACCOUNT}@${GCP_ADMIN_PROJECT_NAME}.iam.gserviceaccount.com" \
    --role "roles/${role}"
done

# Create the bucket which will contain the Terraform state.
gsutil mb -p "${GCP_ADMIN_PROJECT_NAME}" "gs://${TF_STATE_BUCKET_NAME}"

# Enable versioning on the Terraform state bucket.
gsutil versioning set on "gs://${TF_STATE_BUCKET_NAME}"

# Barf a Terraform backend file.
cat > "environments/admin/backend.tfvars" <<EOF
bucket  = "${TF_STATE_BUCKET_NAME}"
prefix  = "terraform/state"
EOF

# Barf a shell environment file to source for running Terraform.
cat > "environments/admin/google.env" <<EOF
export GOOGLE_APPLICATION_CREDENTIALS="${TF_CREDENTIALS_FILE}"
export GOOGLE_PROJECT="${GCP_ADMIN_PROJECT_NAME}"
EOF
