#!/bin/bash

set -xeuo pipefail

# shellcheck disable=SC1090,SC1091
source "environments/admin/credentials.env"

set +e
if ! gcloud projects list | grep --quiet "${GOOGLE_ENVIRONMENT}"; then
  echo "ERROR: Project for ${GOOGLE_ENVIRONMENT} not found"
  exit 1
fi
set -e

GOOGLE_PROJECT_ID=$(
  gcloud projects list \
    | grep "${GOOGLE_ENVIRONMENT}" \
    | awk '{ print $2 }'
)

GOOGLE_CLUSTER_ID=$(
  gcloud container clusters list --project="${GOOGLE_PROJECT_ID}" --limit=1 \
    | tail -n 1 \
    | awk '{ print $1 }'
)

GOOGLE_CLUSTER_REGION=$(
  gcloud container clusters list --project="${GOOGLE_PROJECT_ID}" --limit=1 \
    | tail -n 1 \
    | awk '{ print $2 }'
)

gcloud container clusters get-credentials \
  "${GOOGLE_CLUSTER_ID}" \
  --project "${GOOGLE_PROJECT_ID}" \
  --region "${GOOGLE_CLUSTER_REGION}"
